trigger:
  branches:
    include:
    - master
    - develop
    - fix/*
    - feature/*
pr:
  branches:
    include:
    - master
    - develop

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    strategy:
      matrix:
        'Windows':
          VM_IMAGE: 'windows-latest'
        #'Linux':
        #  VM_IMAGE: 'ubuntu-latest'
        #'macOS':
        #  VM_IMAGE: 'macOS-latest'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - pwsh: ./build.ps1 RunTest
    - displayName: '[Nuke Build]'