trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - fix/*
    - feature/*
pr:
  branches:
    include:
    - master
    - develop

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    strategy:
      matrix:
        'Windows':
          VM_IMAGE: 'windows-latest'
        #'Linux':
        #  VM_IMAGE: 'ubuntu-latest'
        #'macOS':
        #  VM_IMAGE: 'macOS-latest'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - pwsh: ./build.ps1 CreateNuGetPackages
      displayName: '[Nuke Build]'
    - pwsh: ls .
      displayName: 'List .'
    - pwsh: ls $(Build.SourcesDirectory)
      displayName: 'List source dir'
    #- task: DotNetCoreCLI@2
    #  displayName: "Publish NuGet packages"
    #  inputs:
    #    command: 'push'
    #    packagesToPush: '$(Build.SourcesDirectory)/artifacts/*.nupkg'
    #    nuGetFeedType: 'internal'
    #    publishVstsFeed: 'Core/testing'
