trigger:
  branches:
    include:
    - master
    - develop
    - fix/*
    - feature/*
pr:
  branches:
    include:
    - master
    - develop

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    strategy:
      matrix:
        'Windows':
          VM_IMAGE: 'windows-latest'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - pwsh: ./build.ps1 CreateNuGetPackages
      continueOnError: true
      displayName: '[Nuke Build]'
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testResultsFormat: XUnit
        testResultsFiles: '$(Build.SourcesDirectory)/artifacts/test_results/*.xml'
    - task: DotNetCoreCLI@2
      displayName: "Publish NuGet packages"
      condition: succeeded()
      inputs:
        command: 'push'
        packagesToPush: '$(Build.SourcesDirectory)/artifacts/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'Core/testing'    
