name: CI pipeline

on: [push]

jobs:
  build:
    name: Build, test and deploy to github pkg
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/CreativeCodersTeam/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Prepare environment
        run: |
          dotnet tool install --global GitVersion.Tool

      - name: Build Solution
        shell: pwsh
        run: ./build.ps1 CreateNuGetPackages

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests Checks
          path: .tests/results/*.trx
          reporter: dotnet-trx

      - name: Publish the package to GPR
        run: dotnet nuget push .artifacts/**/*.nupkg --skip-duplicate -k ${{secrets.GITHUB_TOKEN}}

      #- name: list sources
      #  run: dotnet-gitversion
