name: pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact-suffix: linux
          - os: windows-latest
            artifact-suffix: windows
          - os: macos-latest
            artifact-suffix: macos
    env:
      TERM: xterm
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: 'Cache: ~/.nuget/packages'
        uses: actions/cache@v5
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Build with target: Pack'
        run: ./build.cmd -t pack
      - name: 'Publish: coverage_report'
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report-${{ matrix.artifact-suffix }}
          path: .tests/coverage-report
