using System;
using JetBrains.Annotations;
using Microsoft.IdentityModel.Tokens;

namespace CreativeCoders.AspNetCore.TokenAuthApi.Jwt;

/// <summary>
///     Options for configuring JWT token authorization API.
/// </summary>
[PublicAPI]
public class JwtTokenAuthApiOptions
{
    /// <summary>
    ///     Gets or sets the security key for token creation and validation.
    /// </summary>
    public SecurityKey? SecurityKey { get; set; }

    /// <summary>
    ///     Gets or sets the time period for which the JWT token remains valid.
    /// </summary>
    /// <value>
    ///     An instance of <see cref="TimeSpan" /> that specifies the duration for which the JWT token should remain valid.
    /// </value>
    /// <remarks>
    ///     The JWT token generated by the authentication API will remain valid for the duration specified by this property.
    ///     Once the token is expired, a new token must be generated/issued.
    /// </remarks>
    public TimeSpan ExpirationTimeSpan { get; set; } = TimeSpan.FromMinutes(30);
}
